FROM {{ cookiecutter.docker_repo }}/{{ cookiecutter.svc_name }}:base-1.0.0
MAINTAINER {{ cookiecutter.author }} <{{ cookiecutter.email }}>

ADD ./{{ cookiecutter.svc_name}} /{{ cookiecutter.svc_name}}/{{ cookiecutter.svc_name}}
ADD ./manage.py /{{ cookiecutter.svc_name}}
